
export const hadeesList: string[] = [
    "The Prophet (ﷺ) said, 'If anyone of you rouses from sleep and performs the ablution, he should wash his nose by putting water in it and then blowing it out thrice, because Satan has stayed in the upper part of his nose all the night.' - Sahih al-Bukhari 3295",
    "A man came to the Prophet (ﷺ) and said, 'I have seen in a dream last night...' The Prophet (ﷺ) said, 'When you see a dream, do not tell it to anyone but to a person who is a sincere friend or a man of sound judgment.' - Jami` at-Tirmidhi 2279",
    "The Prophet (ﷺ) used to say upon waking up: 'Al-hamdu lillahil-ladhi ahyana ba'da ma amatana, wa ilaihin-nushur' (All praise is for Allah who gave us life after having taken it from us and unto Him is the resurrection). - Sahih al-Bukhari 6312",
    "The Prophet (ﷺ) said, 'A good dream that comes true is from Allah, and a bad dream is from Satan.' - Sahih al-Bukhari 6984",
    "When the Prophet (ﷺ) went to bed, he would lie on his right side and then say, 'Allahumma aslamtu nafsi ilaika...' (O Allah! I surrender to You and entrust my affairs to You...). - Sahih al-Bukhari 6313",
    "The Prophet (ﷺ) said, 'When the time draws near (the Day of Judgment), the dream of a believer will hardly be false.' - Sahih al-Bukhari 7017",
    "The Prophet (ﷺ) said, 'Do not lie on your stomach, for it is a position that Allah dislikes.' - Jami` at-Tirmidhi 2768",
    "The Prophet (ﷺ) said: 'Dreams are of three types: a dream from Allah, a dream which causes distress and which comes from the Shaytan, and a dream which comes from what a person thinks about when he is awake.' - Sunan Ibn Majah 3907",
    "The Prophet (ﷺ) said, 'When you go to bed, perform ablution as you would for prayer, then lie down on your right side.' - Sahih al-Bukhari 247",
    "The Prophet (ﷺ) said, 'Whoever sees me in a dream has indeed seen me, for Satan cannot impersonate me.' - Sahih al-Bukhari 6993",
    "The Prophet (ﷺ) said: 'When one of you sees a dream that he likes, it is from Allah, so let him praise Allah for it and tell people about it.' - Sahih al-Bukhari 6985",
    "The Prophet (ﷺ) said: 'But if he sees something other than that, that he dislikes, it is from the Shaytan, so let him seek refuge with Allah from its evil and not mention it to anyone, for it will not harm him.' - Sahih al-Bukhari 6985",
    "Aisha said: 'The Messenger of Allah (ﷺ) used to sleep during the first part of the night and get up during the last part to pray.' - Sahih Muslim 745a",
    "The Prophet (ﷺ) said, 'The truest dream is the one seen at the time of dawn.' - Jami` at-Tirmidhi 2274",
    "The Prophet (ﷺ) forbade sleeping on one's stomach. - Sunan Abi Dawud 5040",
    "The Prophet (ﷺ) said, 'Yawning is from Satan. If you are about to yawn, you should try to stop it as much as possible.' - Sahih al-Bukhari 3289",
    "It was narrated that Ya'ish bin Tikhfah Al-Ghifari said: 'My father was one of the companions of the Suffah... He said: 'I was sleeping in the mosque on my stomach, and a man moved me with his foot and said: 'This is a kind of sleep that Allah, the Mighty and Sublime, dislikes.' I looked, and it was the Messenger of Allah (ﷺ).' - Sunan an-Nasa'i 1187",
    "The Prophet (ﷺ) said, 'When you go to bed, put out your lamps.' - Sahih al-Bukhari 6293",
    "The Prophet (ﷺ) said, 'Dreams are a part of prophethood.' - Jami` at-Tirmidhi 2270",
    "The Prophet (ﷺ) used to recite Surah Al-Ikhlas, Surah Al-Falaq, and Surah An-Nas into his palms and then wipe as much of his body as he could, starting with his head, face, and the front of his body, before sleeping. He would do this three times. - Sahih al-Bukhari 5017",
    "The Prophet (ﷺ) said, 'Taking a nap (Qailulah) is a good habit, for the devils do not take a nap.' - Al-Silsilah al-Sahihah 1647",
    "The Prophet (ﷺ) said, 'If somebody has a dream, he should not narrate it to others if it is a bad one, and he should spit on his left side (thrice) and seek refuge with Allah from Satan.' - Sahih Muslim 2261c",
    "The Prophet (ﷺ) said, 'Cover your vessels, tie your water skins, close your doors and extinguish your lamps, for Satan does not untie a water skin, nor open a door, nor uncover a vessel.' - Sahih Muslim 2012a",
    "Anas ibn Malik reported: The Prophet (ﷺ) would not sleep until he had recited Surah As-Sajdah (32) and Surah Al-Mulk (67). - Jami` at-Tirmidhi 2892",
    "The Prophet (ﷺ) said, 'Whoever recites the last two verses of Surah Al-Baqarah at night, they will be sufficient for him.' - Sahih al-Bukhari 5009",
    "The Prophet (ﷺ) said, 'Dreams are of three kinds: the reflection of one's thoughts and experiences, a dream from Satan to frighten the dreamer, or a glad tiding from Allah.' - Sahih Muslim 2263a",
    "The Prophet (ﷺ) used to make this supplication when he went to bed: 'Bismika Rabbi wada'tu janbi, wa bika arfa'uhu...' (In Your name my Lord, I lie down and in Your name I rise...). - Sahih al-Bukhari 6320",
    "When you lie down on your bed, recite Ayat al-Kursi (2:255) until you complete it, for then a guardian from Allah will be appointed to protect you, and no devil will come near you until morning. - Sahih al-Bukhari 2311",
    "The Prophet (ﷺ) said, 'Whoever wakes up at night and says: ‘La ilaha ill-Allah wahdahu la sharika lah...’ and then says, ‘O Allah, forgive me,’ will be forgiven.' - Sahih al-Bukhari 1154",
    "The Prophet (ﷺ) said, 'When one of you goes to sleep, Satan ties three knots at the back of his head, saying, 'You have a long night, so sleep.' If he wakes up and remembers Allah, one knot is untied. If he performs ablution, the second knot is untied. And if he prays, the third knot is untied, and he gets up energetic and cheerful, otherwise he gets up lazy and in a bad mood.' - Sahih al-Bukhari 1142",
    "Aisha said: 'When the Prophet (ﷺ) got up at night, he would start his prayer with two short rak'ahs.' - Sahih Muslim 768a",
    "The Prophet (ﷺ) said: 'There is an hour during the night in which no Muslim man asks Allah for anything of the good of this world and the Hereafter, but He will give it to him, and that is every night.' - Sahih Muslim 757",
    "The Prophet (ﷺ) said: 'The most beloved prayer to Allah is that of David, and the most beloved fasting to Allah is that of David. He used to sleep half the night, pray for a third of it, and then sleep for a sixth of it.' - Sahih al-Bukhari 1131",
    "The Prophet (ﷺ) said: 'True dreams are one of the forty-six parts of Prophethood.' - Sahih al-Bukhari 6983",
    "The Prophet (ﷺ) said: 'When one of you feels drowsy during prayer, let him sleep until he is fresh, for if he prays while he is drowsy, he may not know whether he is asking for forgiveness or cursing himself.' - Sahih al-Bukhari 212",
    "The Prophet (ﷺ) forbade sleeping before the night prayer and talking after it. - Sahih al-Bukhari 568",
    "It was narrated that Hudhaifah said: 'When the Prophet (ﷺ) wanted to sleep, he would put his right hand under his right cheek and say: 'Allahumma qini 'adhabaka yawma tab'athu 'ibadaka' (O Allah, save me from Your punishment on the Day You resurrect Your slaves).' - Jami` at-Tirmidhi 3398",
    "The Prophet (ﷺ) said: 'Tie the mouths of your water skins and mention the name of Allah; cover your vessels and mention the name of Allah, even if you only put something across them.' - Sahih al-Bukhari 5624",
    "The Prophet (ﷺ) used to sleep on a leather mattress stuffed with palm fibers. - Sahih al-Bukhari 6456",
    "The Prophet (ﷺ) said, 'Excessive yawning is from the devil.' - Sunan Ibn Majah 971",
    "Aisha (RA) narrated that the Prophet (ﷺ) used to pray eleven rak'ahs at night, and when dawn broke, he would pray two short rak'ahs, then he would lie down on his right side until the mu'adhdhin came to him to announce the prayer. - Sahih al-Bukhari 6310",
    "The Prophet (ﷺ) said, 'Hold on to the night prayer, for it was the practice of the righteous before you. It is a means of قربة (nearness) to your Lord, an expiation for sins, and a deterrent from wrongdoing.' - Jami` at-Tirmidhi 3549",
    "The Prophet (ﷺ) said, 'Our Lord descends to the lowest heaven when one-third of the night remains, and says: 'Who will call upon Me, that I may answer Him? Who will ask of Me, that I may give him? Who will seek My forgiveness, that I may forgive him?'' - Sahih al-Bukhari 1145",
    "The Prophet (ﷺ) said: 'If anyone of you sees a dream which he likes, then it is from Allah, and he should thank Allah for it and narrate it to others.' - Sahih al-Bukhari 7044",
    "The Prophet (ﷺ) said: 'If he sees a dream that he dislikes, then it is from Satan, and he should seek refuge with Allah from its evil and should not mention it to anybody, for it will not harm him.' - Sahih al-Bukhari 7044",
    "Aisha (RA) said, 'The first thing with which the Revelation to the Messenger of Allah (ﷺ) began was true dreams in his sleep. He never saw a dream but it came true like the bright daylight.' - Sahih al-Bukhari 3",
    "The Prophet (ﷺ) said, 'Nothing is left of prophethood except for the glad tidings.' They asked, 'What are the glad tidings?' He said, 'The good dream.' - Sahih al-Bukhari 6990",
    "The Prophet (ﷺ) once said: 'In my sleep I saw myself moving a sword...' This illustrates how dreams could hold symbolic meanings. - Sahih al-Bukhari 7041",
    "The Prophet (ﷺ) said, 'Whoever of you sees a dream, let him not tell it to anyone but a beloved person or a wise one.' - Mustadrak al-Hakim",
    "The Prophet (ﷺ) said: 'Spit on your left three times and seek refuge in Allah from the accursed Satan three times, then turn over on to your other side.' (Upon having a bad dream) - Sahih Muslim 2262a",
    "The Prophet (ﷺ) said: 'There are five things which are part of the Fitra (natural disposition): ...trimming the moustache...' which relates to hygiene before sleep. - Sahih al-Bukhari 5889",
    "The Prophet (ﷺ) taught that before sleeping one should dust their bed. He said, 'When any one of you goes to bed, he should take hold of the corner of his lower garment and dust his bed with it.' - Sahih Muslim 2714a",
    "The Prophet (ﷺ) said: 'The deeds most loved by Allah are those done regularly, even if they are small.' This applies to night prayers and dhikr before sleep. - Sahih al-Bukhari 6464",
    "The Prophet (ﷺ) discouraged sleeping alone. - Musnad Ahmad",
    "The Prophet (ﷺ) said, 'Whoever says: 'Subhan-Allahi wa bihamdihi' one hundred times a day, will be forgiven all his sins even if they were as much as the foam of the sea.' This can be recited before sleep. - Sahih al-Bukhari 6405",
    "The Prophet (ﷺ) said, 'Two words are light on the tongue, heavy in the balance, and beloved to the Most Merciful: Subhan-Allahi wa bihamdihi, Subhan-Allahil-Azim.' A good practice before sleep. - Sahih al-Bukhari 6682",
    "The Prophet (ﷺ) used to say 'Bismika allahumma amootu wa-ahya' (In Your name, O Allah, I die and I live) when he went to sleep. - Sahih al-Bukhari 7394",
    "It is recommended to pray the Witr prayer before sleeping if one is not sure they will wake up for it. The Prophet (ﷺ) said, 'Make your last prayer at night the Witr prayer.' - Sahih al-Bukhari 998",
    "The Prophet (ﷺ) said, 'Do not turn your houses into graves. Verily, Satan does not enter the house where Surah Al-Baqarah is recited.' Reciting it, even parts, before sleep is a protection. - Jami` at-Tirmidhi 2877",
    "The Prophet (ﷺ) instructed us to close the doors at night and mention Allah's name. - Sahih al-Bukhari 3304",
    "The Prophet (ﷺ) said, 'When you hear the crowing of cocks, ask for Allah's blessings for they have seen an angel. And when you hear the braying of donkeys, seek refuge with Allah from Satan for they have seen a devil.' This applies to things one might hear at night. - Sahih al-Bukhari 3303",
    "Anas reported that when the Prophet (ﷺ) went to his bed, he said: 'Praise is due to Allah Who fed us and gave us to drink, and Who is sufficient for us and has given us an abode.' - Sahih Muslim 2715a",
    "The Prophet (ﷺ) said: 'If anyone says in the morning and in the evening: 'Subhan-Allahi wa bihamdihi' one hundred times, no one will bring on the Day of Resurrection anything better than what he has brought, except for someone who has said the same as he said, or more.' - Sahih Muslim 2692",
    "The Prophet (ﷺ) said, 'The dream of a Muslim is one of the forty-five parts of Prophethood.' - Sahih Muslim 2263b",
    "The Prophet (ﷺ) said about a man who slept through the night until morning: 'Satan has urinated in his ears.' - Sahih al-Bukhari 1144",
    "The Prophet (ﷺ) said: 'He who goes to bed with an empty stomach, his prayer is not accepted.' (Note: Authenticity of this is debated, but it points to avoiding extreme hunger at bedtime).",
    "The Prophet (ﷺ) said, 'Cleanliness is half of faith.' This includes personal hygiene and cleaning the teeth before sleeping. - Sahih Muslim 223",
    "The Prophet (ﷺ) said, 'Whoever says: 'La ilaha illallahu wahdahu la sharika lahu...' 10 times in the morning, Allah will write for him 100 good deeds and forgive 100 bad deeds...' This dhikr can be done before sleep. - Sahih (Al-Albani)",
    "The Prophet (ﷺ) advised against sleeping on rooftops that have no fence or wall. - Sunan Abi Dawud 5041",
    "The Prophet (ﷺ) said, 'When a fly falls in the drink of anyone of you, he should dip it (in the drink), for one of its wings has a disease and the other has the cure for the disease.' Covering drinks at night is related to this. - Sahih al-Bukhari 3320",
    "The Prophet (ﷺ) used to engage in Istighfar (seeking forgiveness) frequently, a good practice for the end of the day. - Sahih al-Bukhari 6307",
    "The Prophet (ﷺ) said: 'If you see a funeral procession, stand up.' This shows respect for the transition from life to death, a theme related to sleep, the 'minor death'. - Sahih al-Bukhari 1307",
    "The Prophet (ﷺ) said, 'A believer's dream is a part of forty-six parts of prophethood.' - Sahih al-Bukhari 6987",
    "The Prophet (ﷺ) said, 'Do not wish for death, but if you must, say: 'O Allah, keep me alive as long as life is good for me and let me die if death is better for me.'' - Sahih al-Bukhari 5671",
    "The Prophet (ﷺ) taught a supplication for anxiety and sorrow, which can be helpful for those who struggle to sleep: 'Allahumma inni a'udhu bika minal-hammi wal-hazan...' - Sahih al-Bukhari 2893",
    "The Prophet (ﷺ) used to fast on Mondays and Thursdays, impacting his daily and nightly routines. - Jami` at-Tirmidhi 747",
    "The Prophet (ﷺ) said to Fatimah and Ali: 'Shall I not teach you something better than what you have asked for? When you go to bed, say 'SubhanAllah' thirty-three times, 'Alhamdulillah' thirty-three times, and 'Allahu Akbar' thirty-four times.' - Sahih al-Bukhari 3113",
    "The Prophet (ﷺ) said, 'The pen is lifted from three: the sleeping person until he awakens, the child until he reaches puberty, and the insane person until he comes to his senses.' - Sunan an-Nasa'i 3432",
    "The Prophet (ﷺ) said, 'Whoever has a dream that he dislikes should not tell it to anyone, but should get up and pray.' - Jami` at-Tirmidhi 2277",
    "The Prophet (ﷺ) said, 'When you are about to sleep, extinguish your lamps, because the mouse may drag the wick and burn the household.' - Sunan Abi Dawud 5247",
    "The Prophet (ﷺ) said, 'If a man wakes his wife at night and they pray two rak'ahs together, they will be recorded among the men and women who remember Allah much.' - Sunan Abi Dawud 1309",
    "The Prophet (ﷺ) said, 'Whoever among you is afflicted with a dream he dislikes, let him spit on his left three times, and seek refuge with Allah from Satan three times, then change the side he was sleeping on.' - Sunan Ibn Majah 3909",
    "The Prophet (ﷺ) said: 'If anyone of you has a dream, he should not tell it to anyone but to a person whom he loves.' - Sahih Muslim 2261a",
    "The Prophet (ﷺ) said that lying is the worst kind of falsehood, and this includes lying about a dream one has not seen. - Sahih al-Bukhari 7043",
    "The Prophet (ﷺ) said, 'The sleep of the morning prevents one from receiving his provision (rizq).' (Note: Authenticity disputed, but reflects a value on early rising). - Musnad Ahmad",
    "The Prophet (ﷺ) said, 'Verily, your own self has a right over you, your Lord has a right over you, your guest has a right over you, and your wife has a right over you. So, give every owner his right.' This includes the right of the body to rest. - Sahih al-Bukhari 1975",
    "The Prophet (ﷺ) said, 'He is not a believer who eats his fill while his neighbor beside him is hungry.' This points to having a clear conscience before sleep. - Al-Adab Al-Mufrad 112",
    "The Prophet (ﷺ) said, 'The best of you are those who are best to their wives.' A peaceful home life is conducive to good sleep. - Jami` at-Tirmidhi 3895",
    "The Prophet (ﷺ) said, 'There is no envy except in two cases: a person whom Allah has given wealth and he spends it righteously, and a person whom Allah has given wisdom and he judges and teaches with it.' Thinking on these things before sleep is better than envy. - Sahih al-Bukhari 73",
    "The Prophet (ﷺ) said, 'Beware of suspicion, for suspicion is the most false of tales.' Clearing the mind of suspicion before sleep is important. - Sahih al-Bukhari 5143",
    "The Prophet (ﷺ) said, 'The strong man is not the one who wrestles, but the one who controls himself when he is angry.' Controlling anger before sleep leads to peace. - Sahih al-Bukhari 6114",
    "The Prophet (ﷺ) said, 'A true dream is from Allah and a false dream is from Satan.' - Sahih Muslim 2261b",
    "The Prophet (ﷺ) said, 'Whoever reads Surah al-Mulk every night, Allah will protect him from the torment of the grave.' - Sahih (Al-Albani)",
    "The Prophet (ﷺ) used to blow into his hands and recite the Mu'awwidhat (Surah Al-Ikhlas, Al-Falaq, An-Nas) before sleeping. - Sahih al-Bukhari 5748",
    "The Prophet (ﷺ) said to his companions, 'Is any one of you unable to recite a third of the Qur'an in a night?' They said, 'How could we do that?' He said, '(Surah) Qul Huwa Allahu Ahad is equivalent to a third of the Qur'an.' (Recommended before sleep) - Sahih al-Bukhari 5015",
    "The Prophet (ﷺ) said: 'Angels do not enter a house in which there is a dog or a picture.' This speaks to the environment of the bedroom. - Sahih al-Bukhari 3322",
    "The Prophet (ﷺ) said, 'The night prayers are to be prayed in pairs, and if you fear that dawn is approaching, then pray one rak'ah of Witr.' - Sahih al-Bukhari 472",
    "The Prophet (ﷺ) said, 'Do not sleep after the 'Asr prayer, for one might lose his mind.' (Note: This is a weak hadith).",
    "It was narrated that Abu Hurairah said: 'My dear friend (the Prophet) advised me to do three things... to pray Witr before I sleep.' - Sahih al-Bukhari 1178",
    "The Prophet (ﷺ) said, 'When a person is sleeping, Shaytan ties three knots at the back of his head...' (repetition for emphasis on waking for Fajr). - Sahih al-Bukhari 3269",
    "The Prophet (ﷺ) said, 'The best sleep is that of Dawud (David), who would sleep for half the night, stand for a third, and sleep for a sixth.' - Sunan an-Nasa'i 1629",
    "The Prophet (ﷺ) used to take a short nap (qaylulah) in the middle of the day. - Sahih al-Bukhari 6281",
    "The Prophet (ﷺ) said, 'When sleepiness overcomes one of you while he is praying, he should lie down till his sleepiness is over...' - Sahih al-Bukhari 212",
    "The Prophet (ﷺ) said, 'Yawning is from Satan, so if any of you feels like yawning, let him suppress it as much as he can.' - Sahih Muslim 2994a",
    "Aisha (RA) was asked about the prayer of the Prophet (ﷺ) at night. She said, 'He used to sleep during the early part of the night and stood in prayer during the latter part.' - Sahih al-Bukhari 1146",
    "The Prophet (ﷺ) said: 'When you go to your bed, say: 'Allahumma bismika amutu wa ahya' (O Allah, with Your name I die and live).' - Sahih al-Bukhari 6324",
    "The Prophet (ﷺ) used to say upon waking: 'Praise be to Allah Who has returned my soul to me and has given me health in my body and has permitted me to remember Him.' - Jami` at-Tirmidhi 3401",
    "The Prophet (ﷺ) said, 'Indeed, in the remembrance of Allah do hearts find rest.' - Qur'an 13:28 (Not a hadith, but a relevant verse for peaceful sleep).",
    "The Prophet (ﷺ) said, 'Whoever has seen something in a dream that he dislikes, let him stand and pray and not tell people about it.' - Sahih Muslim 2263a",
    "The Prophet (ﷺ) said, 'The interpretation of a dream is according to how it is interpreted, and it is as its interpreter says.' - Sunan Ibn Majah 3914"
];
